---
# ES and Kibana resources
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-dev
  namespace: development
spec:
  version: 8.15.4
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
      xpack.security.audit.enabled: true
      xpack.security.audit.logfile.events.include: "authentication_success"
      xpack.security.audit.logfile.events.emit_request_body: true
      xpack.security.audit.logfile.events.ignore_filters.system.users: ["*_system", "found-internal-*",  "_xpack_security", "_xpack", "elastic/fleet-server","_async_search", "found-internal-admin-proxy"]
      xpack.security.audit.logfile.events.ignore_filters.realm.realms : [ "_es_api_key" ]
      xpack.security.audit.logfile.events.ignore_filters.internal_system.indices : ["*ml-inference-native-*", "*monitoring-es-*"]
      xpack.http.ssl.verification_mode: "none"
    podTemplate:
      metadata:
        labels:
          scrape: es
        annotations:
          co.elastic.logs/enabled: "true"
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: es-mon
        namespace: observability
    logs:
      elasticsearchRefs:
      - name: es-mon
        namespace: observability
  auth:
    fileRealm:
    - secretName: elastic-credentials
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kb-dev
  namespace: development
spec:
  version: 8.15.4
  count: 1
  elasticsearchRef:
    name: es-dev
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: es-mon
        namespace: observability
    logs:
      elasticsearchRefs:
      - name: es-mon
        namespace: observability
  config:
    # https://www.elastic.co/guide/en/kibana/current/monitoring-metricbeat.html
    monitoring.kibana.collection.enabled: false
    xpack.security.audit.enabled: true
    xpack.security.audit.ignore_filters:
    - categories: [web]
    - actions: [saved_object_open_point_in_time, saved_object_close_point_in_time, saved_object_find, space_find]
  podTemplate:
    metadata:
      labels:
        scrape: kb
      annotations:
        co.elastic.logs/enabled: "true"
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=1024"
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 1.5Gi
            cpu: 1